---
abstract: 'Encode UUIDs to be more concise or communicable'
author:
  - 'Nathaniel Reindl <nrr@corvidae.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300013, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-UUID-Concise
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Data::UUID::Concise:
    file: lib/Data/UUID/Concise.pm
    version: 0.121082
requires:
  Carp: 0
  Data::UUID: 0
  Math::BigInt: 0
  Moo: 0
  MooX::Types::MooseLike::Base: 0
  charnames: 0
  feature: 0
  open: 0
  perl: 5.010
  strict: 0
  strictures: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/nrr/Data-UUID-Concise/issues
  homepage: https://github.com/nrr/Data-UUID-Concise
  repository: https://github.com/nrr/Data-UUID-Concise.git
version: 0.121082
